### ISSUE TITLE
bonjour

### ISSUE THREAD

**Issue by davidjr972** [RobyBioloid/jarvis-leMonde#1]
je n'arrive pas a faire fonctionner le plugin il comprend bien mes mots mais ne marche pas

**Comment by RobyBioloid** [comment]
Bonjour.
Sans plus d'information je ne peux pas faire grand chose.
Il faudrait lancer 'Jarvis' en mode de bug et déposer ici le résultat

**Comment by davidjr972** [comment]
bonjour, voila :
jarvis
DEBUG: entering_cmd hook
David: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 5 silence 1 0.1 1 1 0.5 1 trim 0 5
DEBUG: speech duration was 25 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=9c72efec-b7ee-480c-991c-433c9a252687&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"quelles sont les actualités du jour","lexical":"quelles sont les actualités du jour","properties":{"requestid":"452fa8d2-6869-4a6e-978b-f533d79ed954","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"quelles sont les actualités du jour","lexical":"quelles sont les actualités du jour","confidence":"0.9193495","properties":{"HIGHCONF":"1"}}]}
quelles sont les actualités du jour
$> echo "" > ~/jarvis/plugins/jarvis-leMonde/python/news.txt && jv_leMonde_dayNews
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins/jarvis-leMonde/python/dayNews.py", line 3, in <module>
    import lxml.html
ImportError: No module named lxml.html

merci pour l'aide

**Comment by RobyBioloid** [comment]
Il te manque le module lxml
Essaie de l'installer à la main
sudo apt-get install python3-lxml

**Comment by davidjr972** [comment]
bonsoir j'ai essayé il me dit qu'il et deja a jour 
pi@adjrd01:~/jarvis $ sudo apt-get install python3-lxml
sudo: unable to resolve host adjrd01
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
python3-lxml est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 20 non mis à jour.

**Comment by davidjr972** [comment]
David: quels sont les actualités du jour
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins/jarvis-leMonde/python/dayNews.py", line 3, in <module>
    import lxml.html
ImportError: No module named lxml.html

pi@adjrd01:~/jarvis/plugins/jarvis-leMonde/python $ ls
addFavoriteNews.py  favoriteNews.py   news.py   removeFavoriteNews.py
dayNews.py          favoriteNews.txt  news.txt  rubrique.txt

je n'ai pas de module lxml.html dans le dossier python

**Comment by StoneIsland85** [comment]
Salut,
Même constat que pour toi davidjr972. J'obtiens le même message en mode troubleshooting et lorsque je tente d'installer le module lxml, je reviens au même point.
Y'a t'il une solution à ce jour?

**Comment by davidjr972** [comment]
Bonjour
pour résoudre ce problème, j'ai réinstallé lxlm comme ci-dessous (mettre la bonne version ici 3.4.7) : 
pip install lxml
pip install lxml==3.4.7

ça a marché pour moi.

**Comment by RobyBioloid** [comment]
Désolé mais je n'étais pas disponible ces derniers jours

Le problème est il réglé?

**Comment by StoneIsland85** [comment]
Pas de soucis, je suis pas mal occupé aussi.
Concernant ce problème j'ai normalement réussi à récupérer le module lxml mais j'ai toujours un souci qui semble différent de celui-ci.
J'ai donc ouvert un ticket séparé pour plus de clarté.
